### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/spring-eo-kafka#16]

**Comment by h1alexbel** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@h1alexbel I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@h1alexbel I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by h1alexbel** [comment]
@zoeself try again

**Comment by zoeself** [comment]
> @zoeself try again

@h1alexbel didn't understand that, sorry.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-04-19T06:10:11.618637``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
